SRC_DIR=src
BIN_DIR=bin
OBJ_DIR=obj
TLS12_CLIENT = tls12_client
TLS12_SERVER = tls12_server
TLS12_VERF_CB_CLIENT = tls12_verify_cb_client
TLS12_VERF_CB_SERVER = tls12_verify_cb_server
TLS13_CLIENT = tls13_client
TLS13_SERVER = tls13_server
TLS13_CLIENT_DHE = tls13_client_dhe
TLS13_SERVER_DHE = tls13_server_dhe
TLS13_RESUMPTION_CLIENT = tls13_resumption_client
TLS13_RESUMPTION_SERVER = tls13_resumption_server
TARGET=$(TLS12_CLIENT) $(TLS12_SERVER) $(TLS13_CLIENT_DHE) $(TLS13_SERVER_DHE) $(TLS12_VERF_CB_CLIENT) $(TLS12_VERF_CB_SERVER) $(TLS13_CLIENT) $(TLS13_SERVER) $(TLS13_RESUMPTION_CLIENT) $(TLS13_RESUMPTION_SERVER)

COMMON_SRC=$(SRC_DIR)/common
COMM_SRC_FILES=$(wildcard $(COMMON_SRC)/*.c)
TLS12_CLIENT_SRC=$(TLS12_CLIENT).c $(COMM_SRC_FILES)
TLS12_SERVER_SRC=$(TLS12_SERVER).c $(COMM_SRC_FILES)
TLS12_VERF_CB_CLIENT_SRC=$(TLS12_VERF_CB_CLIENT).c $(COMM_SRC_FILES)
TLS12_VERF_CB_SERVER_SRC=$(TLS12_VERF_CB_SERVER).c $(COMM_SRC_FILES)
TLS13_CLIENT_SRC=$(TLS13_CLIENT).c $(COMM_SRC_FILES)
TLS13_SERVER_SRC=$(TLS13_SERVER).c $(COMM_SRC_FILES)
TLS13_CLIENT_DHE_SRC=$(TLS13_CLIENT_DHE).c $(COMM_SRC_FILES)
TLS13_SERVER_DHE_SRC=$(TLS13_SERVER_DHE).c $(COMM_SRC_FILES)
TLS13_RESUMPTION_CLIENT_SRC=$(TLS13_RESUMPTION_CLIENT).c $(COMM_SRC_FILES)
TLS13_RESUMPTION_SERVER_SRC=$(TLS13_RESUMPTION_SERVER).c $(COMM_SRC_FILES)

TLS12_CLIENT_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS12_CLIENT_SRC:.c=.o))
TLS12_SERVER_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS12_SERVER_SRC:.c=.o))
TLS12_VERF_CB_CLIENT_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS12_VERF_CB_CLIENT_SRC:.c=.o))
TLS12_VERF_CB_SERVER_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS12_VERF_CB_SERVER_SRC:.c=.o))
TLS13_CLIENT_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_CLIENT_SRC:.c=.o))
TLS13_SERVER_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_SERVER_SRC:.c=.o))
TLS13_CLIENT_DHE_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_CLIENT_DHE_SRC:.c=.o))
TLS13_SERVER_DHE_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_SERVER_DHE_SRC:.c=.o))
TLS13_RESUMPTION_SERVER_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_RESUMPTION_SERVER_SRC:.c=.o))
TLS13_RESUMPTION_CLIENT_OBJ=$(addprefix $(OBJ_DIR)/,$(TLS13_RESUMPTION_CLIENT_SRC:.c=.o))

DEPENDENCY_DIR=dependency
OPENSSL_1_1_1=openssl-1.1.1a
OPENSSL_1_1_1_DIR=$(DEPENDENCY_DIR)/$(OPENSSL_1_1_1)
OPENSSL_1_1_1_LIBS=$(OPENSSL_1_1_1_DIR)/libssl.a
DEPENDENCY = $(OPENSSL_1_1_1_LIBS)

CFLAGS = -g -ggdb -Wall -Werror -I $(OPENSSL_1_1_1_DIR)/include -I $(COMMON_SRC)
LDFLAGS = $(OPENSSL_1_1_1_DIR)/libssl.a $(OPENSSL_1_1_1_DIR)/libcrypto.a -lpthread -ldl

CC = gcc
CP = cp
RM = rm

#.PHONY all init_task clean

all : init_task build_dependency $(TARGET)

$(OBJ_DIR)/%.o:%.c
	$(CC) $(CFLAGS) -c $< -o $@

build_dependency:$(DEPENDENCY)

$(OPENSSL_1_1_1_LIBS): $(OPENSSL_1_1_1_DIR).tar.gz
	cd $(DEPENDENCY_DIR) && tar -zxvf $(OPENSSL_1_1_1).tar.gz
	cd $(OPENSSL_1_1_1_DIR) && ./config -d
	cd $(OPENSSL_1_1_1_DIR) && make

init_task:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)/$(COMMON_SRC)

$(TLS13_RESUMPTION_SERVER):$(TLS13_RESUMPTION_SERVER_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS13_RESUMPTION_CLIENT):$(TLS13_RESUMPTION_CLIENT_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS13_SERVER_DHE):$(TLS13_SERVER_DHE_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS13_CLIENT_DHE):$(TLS13_CLIENT_DHE_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS13_CLIENT):$(TLS13_CLIENT_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS13_SERVER):$(TLS13_SERVER_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS12_CLIENT):$(TLS12_CLIENT_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS12_SERVER):$(TLS12_SERVER_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS12_VERF_CB_CLIENT):$(TLS12_VERF_CB_CLIENT_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

$(TLS12_VERF_CB_SERVER):$(TLS12_VERF_CB_SERVER_OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

clean:
	@$(RM) -rf *.o *.a
	@$(RM) -rf $(TARGET)
	@$(RM) -rf $(OBJ_DIR) $(BIN_DIR)
